export const X = {
  en: { "login": "Log in", "signup": "Sign up", "logout": "Log out", "phone": "Mobile number", "pass2": "Confirm password", "name": "Full name", "age": "Age", "village": "Village / taluka", "district": "District", "qty": "Onions stored (quintals)", "cap": "Storage size (quintals)", "langPref": "App language", "consent": "I agree to store my data and get alerts", "privacy": "We use your details only to run your storage dashboard and send alerts.", "next": "Next", "back": "Back", "create": "Create account", "haveAcc": "Already have an account?", "noAcc": "New here?", "welcomeBack": "Welcome back", "joinH": "Join OnioRakshak", "demo": "Demo mode: accounts are saved only in this browser.", "s1": "You", "s2": "Your farm", "s3": "Account", "eReq": "Please fill this in", "ePhone": "Enter a 10-digit mobile number", "eAge": "Enter an age from 14 to 100", "ePass": "Use 8+ characters with a letter and a number", "eMatch": "Passwords do not match", "eConsent": "Please tick to continue", "eExists": "This number is already registered", "eBad": "Wrong number or password", "dayH": "From field to chaal, we walk with you", "whatH": "What Rakshak does for you", "wf": [["Live watch", "Temperature, humidity and gas are read every few seconds."], ["Acts on its own", "Fan and curtain move by themselves when the air turns risky."], ["Shelf life", "Know how many days your stock will keep."], ["Price forecast", "See where mandi prices are heading before you sell."], ["Alerts on your phone", "Warnings reach you in Marathi, Hindi or English."], ["Ask by voice", "Ask Rakshak in your own language and get a clear answer."]], "pass": "Password", scenario: 'Try a scenario', pHealthy: 'Healthy store', pWarm: 'Warm and humid', pGas: 'Gas spike', chips: ['What will onion prices do next week?', 'How do I stop onions from sprouting?', 'Why is gas rising in my storage?'], problem: 'Something went wrong', days: 'Days ahead', latest: 'Latest price', in: 'In', dayUnit: 'days', change: 'Change', trend: 'Trend', rising: 'Rising', falling: 'Falling', steady: 'Steady', mode: 'Storage mode', gNow: 'Right now', g24: 'Last 24 hours', gBatch: 'This batch', shelf: 'days of shelf life left', market: 'Market', variety: 'Variety', hist: 'Past prices', fc: 'Forecast', unit: '₹ per quintal', upto: 'Based on data up to', load: 'Loading…',
    sampleData: 'Server did not answer, showing sample data', check: 'Check risk', low: 'Low risk', high: 'High risk', mid: 'Watch closely', local: 'Estimated locally, not by the model',
    ask: 'Ask about prices or storage…', send: 'Send', think: 'Rakshak is thinking…', hello: 'Namaste. Ask me about onion prices or how to keep your stock safe.', fail: 'Could not reach Rakshak. Check that the API is running.' },
  mr: { "login": "लॉग इन", "signup": "नोंदणी करा", "logout": "बाहेर पडा", "phone": "मोबाईल नंबर", "pass2": "पासवर्ड पुन्हा टाका", "name": "पूर्ण नाव", "age": "वय", "village": "गाव / तालुका", "district": "जिल्हा", "qty": "साठवलेला कांदा (क्विंटल)", "cap": "साठवणीची क्षमता (क्विंटल)", "langPref": "अॅपची भाषा", "consent": "माझी माहिती साठवण्यास आणि इशारे मिळवण्यास माझी संमती आहे", "privacy": "तुमची माहिती फक्त तुमचा डॅशबोर्ड चालवण्यासाठी आणि इशारे पाठवण्यासाठी वापरली जाते.", "next": "पुढे", "back": "मागे", "create": "खाते तयार करा", "haveAcc": "आधीच खाते आहे?", "noAcc": "नवीन आहात?", "welcomeBack": "पुन्हा स्वागत", "joinH": "ओनिओरक्षकमध्ये सामील व्हा", "demo": "डेमो मोड: खाती फक्त या ब्राउझरमध्ये साठवली जातात.", "s1": "तुम्ही", "s2": "तुमचे शेत", "s3": "खाते", "eReq": "हे भरा", "ePhone": "10 अंकी मोबाईल नंबर टाका", "eAge": "14 ते 100 दरम्यान वय टाका", "ePass": "किमान 8 अक्षरे, त्यात एक अक्षर आणि एक अंक हवा", "eMatch": "पासवर्ड जुळत नाहीत", "eConsent": "पुढे जाण्यासाठी टिक करा", "eExists": "हा नंबर आधीच नोंदणीकृत आहे", "eBad": "नंबर किंवा पासवर्ड चुकीचा आहे", "dayH": "शेतापासून चाळीपर्यंत, आम्ही तुमच्यासोबत", "whatH": "रक्षक तुमच्यासाठी काय करतो", "wf": [["थेट निरीक्षण", "तापमान, आर्द्रता आणि वायू दर काही सेकंदांनी तपासले जातात."], ["आपोआप कृती", "हवा बिघडली की पंखा आणि पडदा स्वतःच चालतात."], ["टिकण्याचे दिवस", "तुमचा साठा किती दिवस टिकेल ते आधीच कळते."], ["भावाचा अंदाज", "विकण्याआधी मंडी भाव कुठे जात आहेत ते पहा."], ["फोनवर इशारे", "धोक्याची सूचना मराठी, हिन्दी किंवा English मध्ये येते."], ["बोलून विचारा", "रक्षकला तुमच्या भाषेत विचारा, स्पष्ट उत्तर मिळवा."]], "pass": "पासवर्ड", scenario: 'परिस्थिती वापरून पहा', pHealthy: 'निरोगी साठा', pWarm: 'उष्ण आणि दमट', pGas: 'वायू वाढ', chips: ['पुढच्या आठवड्यात कांद्याचे भाव काय होतील?', 'कांद्याला कोंब फुटू नयेत म्हणून काय करावे?', 'माझ्या चाळीत वायू का वाढतोय?'], problem: 'काहीतरी चुकले', days: 'पुढील दिवस', latest: 'आजचा भाव', in: '', dayUnit: 'दिवसांनंतर', change: 'बदल', trend: 'कल', rising: 'वाढता', falling: 'घसरता', steady: 'स्थिर', mode: 'साठवण पद्धत', gNow: 'आत्ता', g24: 'गेले 24 तास', gBatch: 'हा साठा', shelf: 'दिवस टिकण्याची शक्यता', market: 'बाजार', variety: 'वाण', hist: 'मागील भाव', fc: 'अंदाज', unit: '₹ प्रति क्विंटल', upto: 'या तारखेपर्यंतच्या माहितीवर आधारित', load: 'लोड होत आहे…',
    sampleData: 'सर्व्हरकडून उत्तर आले नाही, नमुना माहिती दाखवत आहे', check: 'धोका तपासा', low: 'कमी धोका', high: 'जास्त धोका', mid: 'लक्ष ठेवा', local: 'मॉडेलने नव्हे, स्थानिक अंदाज',
    ask: 'भाव किंवा साठवणीबद्दल विचारा…', send: 'पाठवा', think: 'रक्षक विचार करत आहे…', hello: 'नमस्कार. कांद्याचे भाव किंवा साठा सुरक्षित ठेवण्याबद्दल विचारा.', fail: 'रक्षकशी संपर्क होऊ शकला नाही. API चालू आहे का ते तपासा.' },
  hi: { "login": "लॉग इन", "signup": "साइन अप", "logout": "लॉग आउट", "phone": "मोबाइल नंबर", "pass2": "पासवर्ड दोबारा डालें", "name": "पूरा नाम", "age": "उम्र", "village": "गाँव / तालुका", "district": "ज़िला", "qty": "रखा हुआ प्याज़ (क्विंटल)", "cap": "भंडार की क्षमता (क्विंटल)", "langPref": "ऐप की भाषा", "consent": "मैं अपना डेटा सहेजने और अलर्ट पाने की सहमति देता/देती हूँ", "privacy": "आपकी जानकारी सिर्फ़ आपका डैशबोर्ड चलाने और अलर्ट भेजने में इस्तेमाल होती है।", "next": "आगे", "back": "पीछे", "create": "खाता बनाएँ", "haveAcc": "पहले से खाता है?", "noAcc": "नए हैं?", "welcomeBack": "फिर स्वागत है", "joinH": "ओनिओरक्षक से जुड़ें", "demo": "डेमो मोड: खाते सिर्फ़ इस ब्राउज़र में सहेजे जाते हैं।", "s1": "आप", "s2": "आपका खेत", "s3": "खाता", "eReq": "यह भरें", "ePhone": "10 अंकों का मोबाइल नंबर डालें", "eAge": "14 से 100 के बीच उम्र डालें", "ePass": "कम से कम 8 अक्षर, एक अक्षर और एक अंक रखें", "eMatch": "पासवर्ड मेल नहीं खाते", "eConsent": "आगे बढ़ने के लिए टिक करें", "eExists": "यह नंबर पहले से पंजीकृत है", "eBad": "नंबर या पासवर्ड गलत है", "dayH": "खेत से भंडार तक, हम आपके साथ", "whatH": "रक्षक आपके लिए क्या करता है", "wf": [["लाइव निगरानी", "तापमान, नमी और गैस हर कुछ सेकंड में जाँचे जाते हैं।"], ["अपने-आप कार्रवाई", "हवा बिगड़ते ही पंखा और पर्दा खुद चल पड़ते हैं।"], ["भंडारण के दिन", "आपका स्टॉक कितने दिन टिकेगा, पहले से पता चलता है।"], ["भाव पूर्वानुमान", "बेचने से पहले देखें मंडी भाव किधर जा रहे हैं।"], ["फ़ोन पर चेतावनी", "ख़तरे की सूचना हिन्दी, मराठी या English में आती है।"], ["बोलकर पूछें", "रक्षक से अपनी भाषा में पूछें, साफ़ जवाब पाएँ।"]], "pass": "पासवर्ड", scenario: 'स्थिति आज़माएँ', pHealthy: 'स्वस्थ भंडार', pWarm: 'गर्म और नम', pGas: 'गैस में उछाल', chips: ['अगले हफ़्ते प्याज़ के भाव क्या होंगे?', 'प्याज़ में अंकुर आने से कैसे रोकें?', 'मेरे भंडार में गैस क्यों बढ़ रही है?'], problem: 'कुछ गड़बड़ हुई', days: 'आगे के दिन', latest: 'ताज़ा भाव', in: '', dayUnit: 'दिन बाद', change: 'बदलाव', trend: 'रुझान', rising: 'बढ़ता', falling: 'गिरता', steady: 'स्थिर', mode: 'भंडारण तरीका', gNow: 'अभी', g24: 'पिछले 24 घंटे', gBatch: 'यह स्टॉक', shelf: 'दिन भंडारण-अवधि बची', market: 'बाज़ार', variety: 'किस्म', hist: 'पिछले भाव', fc: 'पूर्वानुमान', unit: '₹ प्रति क्विंटल', upto: 'इस तारीख तक के डेटा पर आधारित', load: 'लोड हो रहा है…',
    sampleData: 'सर्वर से जवाब नहीं मिला, नमूना डेटा दिखा रहे हैं', check: 'जोखिम जाँचें', low: 'कम जोखिम', high: 'ज़्यादा जोखिम', mid: 'नज़र रखें', local: 'मॉडल से नहीं, स्थानीय अनुमान',
    ask: 'भाव या भंडारण के बारे में पूछें…', send: 'भेजें', think: 'रक्षक सोच रहा है…', hello: 'नमस्ते। प्याज़ के भाव या स्टॉक सुरक्षित रखने के बारे में पूछें।', fail: 'रक्षक से संपर्क नहीं हो सका। जाँचें कि API चल रही है।' },
}

// Extra UI strings for the polish pass (merged in App.jsx after X).
export const Y = {
  en: { skip: 'Skip to content', top: 'Back to top', reset: 'Reset', copy: 'Copy', copied: 'Copied', clear: 'Clear chat', hide: 'Hide', show: 'Show', pause: 'Pause video', play: 'Play video', range: 'History', dUnit: 'd', pin: 'Click the chart to pin a value', minmax: 'Range', close: 'Close' },
  mr: { skip: 'मजकुराकडे जा', top: 'वर जा', reset: 'पुन्हा सेट करा', copy: 'कॉपी', copied: 'कॉपी झाले', clear: 'चॅट साफ करा', hide: 'लपवा', show: 'दाखवा', pause: 'व्हिडिओ थांबवा', play: 'व्हिडिओ सुरू करा', range: 'इतिहास', dUnit: 'दि', pin: 'किंमत पाहण्यासाठी आलेखावर क्लिक करा', minmax: 'श्रेणी', close: 'बंद करा' },
  hi: { skip: 'सामग्री पर जाएँ', top: 'ऊपर जाएँ', reset: 'रीसेट', copy: 'कॉपी', copied: 'कॉपी हुआ', clear: 'चैट साफ़ करें', hide: 'छुपाएँ', show: 'दिखाएँ', pause: 'वीडियो रोकें', play: 'वीडियो चलाएँ', range: 'इतिहास', dUnit: 'दिन', pin: 'मान देखने के लिए चार्ट पर क्लिक करें', minmax: 'सीमा', close: 'बंद करें' },
}
