export const X = {
  en: { problem: 'Something went wrong', days: 'Days ahead', latest: 'Latest price', in: 'In', dayUnit: 'days', change: 'Change', trend: 'Trend', rising: 'Rising', falling: 'Falling', steady: 'Steady', mode: 'Storage mode', gNow: 'Right now', g24: 'Last 24 hours', gBatch: 'This batch', shelf: 'days of shelf life left', market: 'Market', variety: 'Variety', hist: 'Past prices', fc: 'Forecast', unit: '₹ per quintal', upto: 'Based on data up to', load: 'Loading…',
    sampleData: 'Server did not answer, showing sample data', check: 'Check risk', low: 'Low risk', high: 'High risk', mid: 'Watch closely', local: 'Estimated locally, not by the model',
    ask: 'Ask about prices or storage…', send: 'Send', think: 'Rakshak is thinking…', hello: 'Namaste. Ask me about onion prices or how to keep your stock safe.', fail: 'Could not reach Rakshak. Check that the API is running.' },
  mr: { problem: 'काहीतरी चुकले', days: 'पुढील दिवस', latest: 'आजचा भाव', in: '', dayUnit: 'दिवसांनंतर', change: 'बदल', trend: 'कल', rising: 'वाढता', falling: 'घसरता', steady: 'स्थिर', mode: 'साठवण पद्धत', gNow: 'आत्ता', g24: 'गेले 24 तास', gBatch: 'हा साठा', shelf: 'दिवस टिकण्याची शक्यता', market: 'बाजार', variety: 'वाण', hist: 'मागील भाव', fc: 'अंदाज', unit: '₹ प्रति क्विंटल', upto: 'या तारखेपर्यंतच्या माहितीवर आधारित', load: 'लोड होत आहे…',
    sampleData: 'सर्व्हरकडून उत्तर आले नाही, नमुना माहिती दाखवत आहे', check: 'धोका तपासा', low: 'कमी धोका', high: 'जास्त धोका', mid: 'लक्ष ठेवा', local: 'मॉडेलने नव्हे, स्थानिक अंदाज',
    ask: 'भाव किंवा साठवणीबद्दल विचारा…', send: 'पाठवा', think: 'रक्षक विचार करत आहे…', hello: 'नमस्कार. कांद्याचे भाव किंवा साठा सुरक्षित ठेवण्याबद्दल विचारा.', fail: 'रक्षकशी संपर्क होऊ शकला नाही. API चालू आहे का ते तपासा.' },
  hi: { problem: 'कुछ गड़बड़ हुई', days: 'आगे के दिन', latest: 'ताज़ा भाव', in: '', dayUnit: 'दिन बाद', change: 'बदलाव', trend: 'रुझान', rising: 'बढ़ता', falling: 'गिरता', steady: 'स्थिर', mode: 'भंडारण तरीका', gNow: 'अभी', g24: 'पिछले 24 घंटे', gBatch: 'यह स्टॉक', shelf: 'दिन भंडारण-अवधि बची', market: 'बाज़ार', variety: 'किस्म', hist: 'पिछले भाव', fc: 'पूर्वानुमान', unit: '₹ प्रति क्विंटल', upto: 'इस तारीख तक के डेटा पर आधारित', load: 'लोड हो रहा है…',
    sampleData: 'सर्वर से जवाब नहीं मिला, नमूना डेटा दिखा रहे हैं', check: 'जोखिम जाँचें', low: 'कम जोखिम', high: 'ज़्यादा जोखिम', mid: 'नज़र रखें', local: 'मॉडल से नहीं, स्थानीय अनुमान',
    ask: 'भाव या भंडारण के बारे में पूछें…', send: 'भेजें', think: 'रक्षक सोच रहा है…', hello: 'नमस्ते। प्याज़ के भाव या स्टॉक सुरक्षित रखने के बारे में पूछें।', fail: 'रक्षक से संपर्क नहीं हो सका। जाँचें कि API चल रही है।' },
}
